# Permalinks
permalink:           pretty

# Setup
title:               Kara Bethany Liu
tagline:             oHai
url:                 http://karawkz.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kara Bethany Liu
  url:               https://https://www.instagram.com/karawkz/?hl=en
  email:             karabethanyliu@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/karawkz

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
